# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

branches:
  except:
  - gh-pages

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - curl -Ls -o gen-index https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/gen-index.sh
  - chmod +x docker-build gen-index

install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build scripts

deploy:
  - provider: pages
    github-token: $GITHUB_TOKEN
    #keep-history: true
    skip_cleanup: true
    committer-from-gh: true
    target-branch: gh-pages
    local-dir: html-report
    on:
      all_branches: true
      condition: ${DISTRO} =~ ^fedora.*$
  - provider: script
    script: ./docker-build --verbose --config .travis.yml --release github
    skip_cleanup: true
    on:
      tags: true
      condition: "${TRAVIS_TAG} =~ ^v.*$ && ${DISTRO} =~ ^fedora.*$"

after_success:
  - 'if [[ "$TRAVIS_SECURE_ENV_VARS" == "true" && "$TRAVIS_PULL_REQUEST" != "false" && ${DISTRO} =~ ^fedora.*$ ]]; then
        REPO_SLUG_ARRAY=(${TRAVIS_REPO_SLUG//\// });
        REPO_NAME=${REPO_SLUG_ARRAY[1]};
        URL="https://${REPO_NAME}.mate-desktop.dev";
        COMMENT="Code analysis completed";
        curl -H "Authorization: token $GITHUB_TOKEN" -X POST
           -d "{\"state\": \"success\", \"description\": \"$COMMENT\", \"context\":\"scan-build\", \"target_url\": \"$URL\"}"
           https://api.github.com/repos/${TRAVIS_REPO_SLUG}/statuses/${TRAVIS_PULL_REQUEST_SHA};
     fi'

env:
  - DISTRO="archlinux/base"
  - DISTRO="debian:sid"
  - DISTRO="fedora:29"
  - DISTRO="ubuntu:18.10"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-control-center
    - clang
    - gcc
    - git
    - gobject-introspection
    - intltool
    - itstool
    - libxss
    - make
    - marco
    - mate-common
    - mate-menus
    - mate-settings-daemon
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-control-center
    - clang
    - clang-tools
    - curl
    - desktop-file-utils
    - git
    - gobject-introspection
    - intltool
    - libcanberra-gtk3-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libdconf-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtop2-dev
    - libmarco-dev
    - libmate-desktop-dev
    - libmate-menu-dev
    - libmatekbd-dev
    - libpango1.0-dev
    - librsvg2-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxcursor-dev
    - libxi-dev
    - libxklavier-dev
    - libxml2-dev
    - libxrandr-dev
    - libxss-dev
    - libxt-dev
    - make
    - mate-common
    - mate-settings-daemon-dev
    - shared-mime-info
    - xsltproc
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-control-center.git
    - cairo-gobject-devel
    - clang
    - clang-analyzer
    - dconf-devel
    - desktop-file-utils
    - gcc
    - git
    - gobject-introspection-devel
    - gtk3-devel
    - iso-codes-devel
    - itstool
    - libSM-devel
    - libXScrnSaver-devel
    - libXxf86misc-devel
    - libcanberra-devel
    - libmatekbd-devel
    - librsvg2-devel
    - make
    - marco-devel
    - mate-common
    - mate-settings-daemon-devel
    - redhat-rpm-config
    - startup-notification-devel
    - which

  ubuntu:
    - curl
    - clang
    - clang-tools
    - desktop-file-utils
    - git
    - gobject-introspection
    - intltool
    - libcanberra-gtk3-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libdconf-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtop2-dev
    - libmarco-dev
    - libmate-desktop-dev
    - libmate-menu-dev
    - libmatekbd-dev
    - libpango1.0-dev
    - librsvg2-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxcursor-dev
    - libxi-dev
    - libxklavier-dev
    - libxml2-dev
    - libxrandr-dev
    - libxss-dev
    - libxt-dev
    - make
    - mate-common
    - mate-settings-daemon-dev
    - shared-mime-info
    - xsltproc
    - yelp-tools

variables:
  - CFLAGS="-Wall -Werror=format-security"
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  - cd ${START_DIR}
  - if [ ! -f mate-desktop-1.22.0.tar.xz ];then
  -     curl -Ls -o mate-desktop-1.22.0.tar.xz https://github.com/mate-desktop/mate-desktop/releases/download/v1.22.0/mate-desktop-1.22.0.tar.xz
  - fi
  - tar xf mate-desktop-1.22.0.tar.xz
  - cd mate-desktop-1.22.0
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./configure --prefix=/usr
  - fi
  - if [ ${TRAVIS} == "false" ]; then
  -     make clean
  - fi
  - make
  - make install

  - cd ${START_DIR}
  - if [ ! -f mate-menus-1.22.0.tar.xz ];then
  -     curl -Ls -o mate-menus-1.22.0.tar.xz https://github.com/mate-desktop/mate-menus/releases/download/v1.22.0/mate-menus-1.22.0.tar.xz
  - fi
  - tar xf mate-menus-1.22.0.tar.xz
  - cd mate-menus-1.22.0
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./autogen.sh --prefix=/usr
  - fi
  - if [ ${TRAVIS} == "false" ]; then
  -     make clean
  - fi
  - make
  - make install

  - cd ${START_DIR}
  - if [ ! -f mate-settings-daemon-1.22.0.tar.xz ]; then
  -     curl -Ls -o mate-settings-daemon-1.22.0.tar.xz https://github.com/mate-desktop/mate-settings-daemon/releases/download/v1.22.0/mate-settings-daemon-1.22.0.tar.xz
  - fi
  - tar xf mate-settings-daemon-1.22.0.tar.xz
  - cd mate-settings-daemon-1.22.0
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./configure --prefix=/usr
  - fi
  - if [ ${TRAVIS} == "false" ]; then
  -     make clean
  - fi
  - make
  - make install

build_scripts:
  - ./autogen.sh
  - scan-build $CHECKERS ./configure
  - scan-build $CHECKERS --keep-cc -o html-report make -j $(( $CPU_COUNT + 1 ))

after_scripts:
  - if [ ${DISTRO_NAME} == "fedora" ];then
  -   ./gen-index -i https://github.com/${OWNER_NAME}/mate-icon-theme/raw/master/mate/16x16/categories/preferences-desktop.png
  - fi
  - make distcheck

releases:
  draft: False
  prerelease: False
  checksum: True
  file_glob: True
  files: mate-control-center-*.tar.xz
  github_release:
    tags: True
    overwrite: True
    base_version: 1.20.0
